### ISSUE TITLE
make: *** [Makefile:136: all] Error 2

### ISSUE THREAD

**Issue by Greyisttot** [KamiliaBlow/RoleplayCore#177]
### Description

/1_source/src/server/game/Entities/Creature/Creature.cpp: In member function ‘virtual void Creature::Update(uint32)’:
/1_source/src/server/game/Entities/Creature/Creature.cpp:765:67: error: no matching function for call to ‘GetUpdateFieldHolderIndex(UF::UpdateField<int, 0, 5> UF::UnitData::)’
  765 |     if (m_outfit && !m_values.HasChanged(GetUpdateFieldHolderIndex(&UF::UnitData::DisplayID)) && Unit::GetDisplayId() == CreatureOutfit::invisible_model)
      |                                          ~~~~~^~~~~~
compilation terminated due to -Wfatal-errors.
make[2]: ** [src/server/game/CMakeFiles/game.dir/build.make:1341: src/server/game/CMakeFiles/game.dir/Entities/Creature/Creature.cpp.o] Error 1
make[2]:  Waiting for unfinished jobs....
/1_source/src/server/game/Entities/GameObject/GameObject.cpp: In member function ‘virtual void GameObject::Update(uint32)’:
/1_source/src/server/game/Entities/GameObject/GameObject.cpp:1341:25: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
 1341 |                         if (caster && caster->GetTypeId() == TYPEID_PLAYER)
      |                         ^~
/1_source/src/server/game/Entities/GameObject/GameObject.cpp:1343:29: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
 1343 |                             SendCustomAnim(0);
      |                             ^~~~~~
make[1]:  [CMakeFiles/Makefile2:1282: src/server/game/CMakeFiles/game.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

### Expected behaviour

-

### Steps to reproduce the problem

-

### Branch

master

### TC rev. hash/commit

-

### Operating system

Ubuntu 22.04

### Custom changes

-

**Comment by KamiliaBlow** [comment]
https://github.com/KamiliaBlow/RoleplayCore/commit/2532d50230d0703a9dd3abe5a6e11beb464a0255
