### ISSUE TITLE
In the ubuntu environment, eluna cannot read subdirectories, like this /bin/lua_scripts/AIO_Server/lualzw-zeros directory, she can only read all scripts in the root directory

### ISSUE THREAD

**Issue by Greyisttot** [KamiliaBlow/RoleplayCore#188]
### Description

In the ubuntu environment, eluna cannot read subdirectories, like this /bin/lua_scripts/AIO_Server/lualzw-zeros directory, she can only read all scripts in the root directory

### Expected behaviour

-

### Steps to reproduce the problem

-

### Branch

master

### TC rev. hash/commit

-

### Operating system

Ubuntu 22.04

### Custom changes

-

**Comment by KamiliaBlow** [comment]
Fixen on commit 994ecff
