### ISSUE TITLE
[Misc] caschost 10x support

### ISSUE THREAD

**Issue by coolzoom** [KamiliaBlow/RoleplayCore#40]
### Description

sorry this is not core related, but the caschost does not have an issues tab so I wish to ask here.
Queen Sylvanas needs some beautiful mods. xD

### Expected behaviour

wish the CASCHost can work with RoleplayCore client

### Steps to reproduce the problem

using [casc](https://github.com/KamiliaBlow/CASCHost_9.1plus)

### Branch

master

### TC rev. hash/commit

https://github.com/KamiliaBlow/RoleplayCore/commit/aae43edf3c4c3a325d9aea04ebe9f07ebad8a656

### Operating system

Windows 10 x64

### Custom changes

custom skin and login screen changes

**Comment by KamiliaBlow** [comment]
Sorry friend, but I can't fix it, because the data structure has changed and the old method of decrypting and overwriting doesn't work.

**Comment by coolzoom** [comment]
no worries, I look forward to the day when we can finally do that, my dear friend.
